ninety_nine_cats/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :cats
end

ninety_nine_cats/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

ninety_nine_cats/app/models/cat.rb
class Cat < ApplicationRecord
  include ActionView::Helpers::DateHelper
  COLORS = ["Black", "Grey", "Calico", "Orange", "Blue", "Tabby", "White"]
  validates :name, :color, :birth_date, :sex, :description, presence: true
  validates :sex, inclusion: {in: %w(M F)}
  validates :color, inclusion: {in: COLORS}

  has_many :rental_requests,
  class_name: 'CatRentalRequest',
  dependent: :destroy


  def age 
    time_ago_in_words(birth_date)
  end 


end

ninety_nine_cats/app/models/cat_rental_request.rb
class CatRentalRequest < ApplicationRecord
  validates :start_date, :end_date, :status, presence: true
  validates :status, inclusion: {in: ["PENDING", "APPROVED", "DENIED"]}
  validate :does_not_overlap_approved_request

  belongs_to :cat

  def overlapping_requests
    if id
      CatRentalRequest.where("(start_date BETWEEN ? AND ?) OR (end_date BETWEEN ? AND ?) AND id != ?", start_date, end_date, start_date, end_date, id)
    else
      CatRentalRequest.where("(start_date BETWEEN ? AND ?) OR (end_date BETWEEN ? AND ?) AND id != ?", start_date, end_date, start_date, end_date)
    end
  end
  
  def overlapping_approved_requests
    overlapping_requests.where(status: "APPROVED")
  end 

  def does_not_overlap_approved_request
    errors.add("requests can't overlap!") if overlapping_approved_requests.exists?
  end 
end

ninety_nine_cats/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

ninety_nine_cats/app/controllers/cats_controller.rb
class CatsController < ApplicationController

  def index 
    @cats = Cat.all

    # render 'index', cats: @cats
  end 

  def show
    @cat = Cat.find(params[:id])
    # render 'show', cat: @cat
  end

  def new
    @cat = Cat.new
    render 'new'    
  end

  def create
    @cat = Cat.new(cat_params)
    if @cat.save!
      redirect_to cat_url(@cat)
    else 
      render @cat.errors.full_message, status: :unprocessable_entity
    end 
  end 

  def edit 
    @cat = Cat.find(params[:id])

    render 'update'
  end 

  def update 

    @cat = Cat.find(params[:id])

    if @cat.persisted? 
      Cat.update(params[:id], cat_params)
      redirect_to cat_url(@cat)
    else 
      render @cat.errors.full_message, status: :not_found
    end 
  end 
  private

  def cat_params
    params.require(:cat).permit(:name, :birth_date, :sex, :color, :description)
  end 
end 

ninety_nine_cats/app/helpers/application_helper.rb
module ApplicationHelper
end

ninety_nine_cats/app/views/cats/_form.html.erb
<% if action == "post" %>
  <% action_url = cats_url %>
  <% button_label = "Add cat to database!" %>
  <h1>Make a Cat!</h1>
<% elsif action == "patch" %>
  <% action_url = cat_url(cat) %>
  <% button_label = "Update a cat!" %>
  <h1>Update a cat!</h1>
<% end %>

<form method="post" action="<%= action_url %>">
  <input type="hidden" name="_method" value="<%= action %>">
<label for="name">Name:
  <input type="text" name="cat[name]" value="<%=cat.name%>">
</label>
<label for="birth_date">Date of Birth:
    <input type="date" name="cat[birth_date]" value="<%=cat.birth_date%>">
</label>
<label for="color">Name:
    <select name="cat[color]">
      <option selected disabled value = "<%=cat.color%>"><%=cat.color ? cat.color : "Pick a color!"%></option>
       <% Cat::COLORS.each do |color| %>
        <option value = <%=color%>><%=color%></option>
      <% end %> 
    </select>
</label>
<label for="sex">Sex:
    <input type="radio" name="cat[sex]" value="M" <%= cat.sex == 'M' ? "checked" : nil %>>Male
    <input type="radio" name="cat[sex]" value="F" <%= cat.sex == 'F' ? "checked" : nil %>>Female
</label>
<br>
<label for="description">About me:
    <textarea name="cat[description]"><%=cat.description%></textarea>
</label>

<input type="submit" value="<%= button_label %>">

</form>

ninety_nine_cats/app/views/cats/index.html.erb
<h1>ALL OF THE CATS!</h1>
<ul>
<% @cats.each do |cat| %>
  <ul>
   <li><%= cat.name %></li>
   <li><%= cat.birth_date %></li>
   <li><%= cat.color %></li>
   <li><%= cat.sex %></li>
   <li><%= cat.description %></li>
   <a href="<%= cat_url(cat) %>">See Me!</a>
   </ul>
<% end %>

</ul>

ninety_nine_cats/app/views/cats/new.html.erb
<%= render 'form', cat: @cat, action: "post" %>

ninety_nine_cats/app/views/cats/show.html.erb
<table>
<thead>
  <tr>
    <th>My name is <%= @cat.name %>!</th>
  </tr>
</thead>
  <tbody>
    <tr>
      <td>name:</td> 
      <td><%= @cat.name %></td>
    </tr>
    <tr>
      <td>I was born on:</td> 
      <td><%= @cat.birth_date %></td>
    </tr>
    <tr>
      <td>age:</td>
      <td><%= @cat.age %></td>
    </tr>
    <tr>
      <td>color:</td>
      <td><%= @cat.color %></td>
    </tr>
    <tr>
      <td>sex:</td>
      <td><%= @cat.sex %></td>
    </tr>
    <tr>
      <td>desc:</td>
      <td><%= @cat.description %></td>
    </tr>
  </tbody>
</table>
<a href="<%= cats_url %>">See ALL the cats!</a>

ninety_nine_cats/app/views/cats/update.html.erb
<%= render 'form', cat: @cat, action: "patch" %>

ninety_nine_cats/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NinetyNineCats</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>